Github desktop produced an error.  Uploading by hand.
To https://github.com/jerryevalentine/pandas-challenge.git
 ! [rejected]        main -> main (stale info)
error: failed to push some refs to 'https://github.com/jerryevalentine/pandas-challenge.git'
I will perform a pull so that the most updated files are in the repository and also on my computer.